
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { AUDIT_AREAS } from '../data/mockData';
import { CheckCircle, XCircle, Search, Paperclip, Plus, X, Sparkles, FileText, Table, Eye } from 'lucide-react';
import type { AuditAreaCode, Scenario } from '../types';

// --- Reusing Basic Evidence Viewer Logic for Detail Modal ---
const GenericDocViewer: React.FC<{ scenario: Scenario }> = ({ scenario }) => {
  const { title } = scenario;
  const isFail = scenario.status === 'Fail';
  return (
    <div className="w-full h-full bg-slate-200 p-4 overflow-hidden flex items-center justify-center rounded-lg border border-slate-300">
         <div className="w-full max-w-2xl bg-white shadow-xl h-full max-h-[500px] overflow-auto flex flex-col transform transition-transform duration-300">
            <div className="p-8 bg-white h-full flex flex-col">
                <div className="border-b-2 border-slate-800 pb-4 mb-6">
                    <div className="flex justify-between items-start">
                        <h1 className="text-xl font-bold uppercase text-slate-800">{title}</h1>
                        <FileText className="w-8 h-8 text-slate-300" />
                    </div>
                    <p className="text-sm text-slate-500 mt-2">Ref: {scenario.id}</p>
                </div>
                <div className="space-y-4 text-sm text-slate-800 leading-relaxed text-justify flex-1">
                    <p>Evidence document for <strong>{title}</strong>.</p>
                    <div className="bg-slate-50 p-4 border border-slate-200 rounded my-4">
                        <h4 className="font-bold mb-2 flex items-center gap-2">
                            <Table className="w-4 h-4 text-slate-500"/> Data Extract (2024-2025)
                        </h4>
                        <div className="space-y-2 text-xs font-mono text-slate-600">
                             <div className="flex justify-between font-bold"><span>Audit Result</span><span className={isFail ? "text-red-600" : "text-green-600"}>{isFail ? "FAIL" : "PASS"}</span></div>
                             <div className="border-t pt-2 mt-2">
                                <p>Analyzed 15,230 records.</p>
                                <p>Matched against "Procurement_Policy_v3.pdf"</p>
                             </div>
                        </div>
                    </div>
                    <p>This document is automatically generated by AuditFlow AI as proof of audit execution.</p>
                </div>
            </div>
         </div>
    </div>
  );
};

// --- Modal for Adding Scenario ---
const AddScenarioModal: React.FC<{
  onClose: () => void;
  onAdd: (data: Omit<Scenario, 'id' | 'status' | 'detailedDescription' | 'timestamp' | 'evidenceUrl' | 'isNew'>) => void;
}> = ({ onClose, onAdd }) => {
    // ... (Keep existing form logic)
    const [title, setTitle] = useState('');
    const [description, setDescription] = useState('');
    const [areaCode, setAreaCode] = useState<AuditAreaCode>('FSC');
    const [risk, setRisk] = useState<'High' | 'Medium' | 'Low'>('Medium');
    const [type, setType] = useState<'Structured' | 'Unstructured'>('Structured');

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (!title || !description) return;
        onAdd({ title, description, areaCode, risk, type });
    };

    return (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={onClose}>
            <motion.div
                initial={{ opacity: 0, y: -30 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -30 }}
                onClick={(e) => e.stopPropagation()}
                className="bg-white rounded-xl shadow-lg w-full max-w-2xl"
            >
                <div className="p-6 border-b flex justify-between items-center">
                    <h2 className="text-lg font-bold">새 감사 시나리오 추가</h2>
                    <button onClick={onClose} className="p-1 rounded-full hover:bg-slate-100"><X className="w-5 h-5"/></button>
                </div>
                <form onSubmit={handleSubmit}>
                    <div className="p-6 space-y-4 max-h-[70vh] overflow-y-auto">
                        <div>
                            <label htmlFor="title" className="block text-sm font-medium text-slate-700 mb-1">시나리오 제목</label>
                            <input type="text" id="title" value={title} onChange={(e) => setTitle(e.target.value)} required className="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500"/>
                        </div>
                        <div>
                            <label htmlFor="description" className="block text-sm font-medium text-slate-700 mb-1">설명 (Description)</label>
                            <textarea id="description" value={description} onChange={(e) => setDescription(e.target.value)} required rows={3} className="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500"/>
                        </div>
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <div>
                                <label htmlFor="areaCode" className="block text-sm font-medium text-slate-700 mb-1">감사 영역</label>
                                <select id="areaCode" value={areaCode} onChange={(e) => setAreaCode(e.target.value as AuditAreaCode)} className="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500 bg-white">
                                    {AUDIT_AREAS.map(area => <option key={area.code} value={area.code}>{area.name}</option>)}
                                </select>
                            </div>
                             <div>
                                <label htmlFor="risk" className="block text-sm font-medium text-slate-700 mb-1">위험 수준</label>
                                <select id="risk" value={risk} onChange={(e) => setRisk(e.target.value as any)} className="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500 bg-white">
                                    <option value="High">High</option>
                                    <option value="Medium">Medium</option>
                                    <option value="Low">Low</option>
                                </select>
                            </div>
                             <div>
                                <label htmlFor="type" className="block text-sm font-medium text-slate-700 mb-1">분석 유형</label>
                                <select id="type" value={type} onChange={(e) => setType(e.target.value as any)} className="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-1 focus:ring-blue-500 bg-white">
                                    <option value="Structured">Structured (정형)</option>
                                    <option value="Unstructured">Unstructured (비정형)</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div className="p-4 bg-slate-50 border-t flex justify-end gap-3">
                        <button type="button" onClick={onClose} className="px-4 py-2 text-sm font-medium bg-white border border-slate-300 rounded-md hover:bg-slate-50">취소</button>
                        <button type="submit" className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700">추가</button>
                    </div>
                </form>
            </motion.div>
        </div>
    );
};

// --- Detail View Modal with Visual Evidence ---
const ScenarioDetailModal: React.FC<{ scenario: Scenario; onClose: () => void }> = ({ scenario, onClose }) => {
    return (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={onClose}>
             <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                onClick={(e) => e.stopPropagation()}
                className="bg-white rounded-xl shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden"
            >
                <div className="p-6 border-b flex justify-between items-start bg-slate-50">
                    <div>
                        <div className="flex items-center gap-2 mb-2">
                             <span className="px-2 py-0.5 rounded bg-white border border-slate-200 text-slate-600 text-xs font-bold">{scenario.areaCode}</span>
                             <span className={`px-2 py-0.5 rounded text-xs font-bold text-white ${scenario.risk === 'High' ? 'bg-red-500' : scenario.risk === 'Medium' ? 'bg-yellow-500' : 'bg-green-500'}`}>{scenario.risk} Risk</span>
                             {scenario.isNew && (
                                <span className="flex items-center gap-1 px-2 py-0.5 rounded text-xs font-bold bg-indigo-100 text-indigo-700 border border-indigo-200">
                                    <Sparkles className="w-3 h-3"/> AI Recommended
                                </span>
                             )}
                        </div>
                        <h2 className="text-xl font-bold text-slate-900">{scenario.title}</h2>
                    </div>
                    <button onClick={onClose} className="p-2 rounded-full hover:bg-slate-200"><X className="w-6 h-6 text-slate-500"/></button>
                </div>
                
                <div className="flex-1 overflow-y-auto p-6 bg-slate-100 flex gap-6">
                    {/* Left: Details */}
                    <div className="w-1/3 space-y-4">
                        <div className="bg-white p-5 rounded-lg shadow-sm border border-slate-200">
                             <h3 className="text-sm font-bold text-slate-500 uppercase mb-3">검증 로직</h3>
                             <p className="text-sm text-slate-700 leading-relaxed">{scenario.detailedDescription}</p>
                        </div>
                        <div className="bg-white p-5 rounded-lg shadow-sm border border-slate-200">
                             <h3 className="text-sm font-bold text-slate-500 uppercase mb-3">결과 상태</h3>
                             <div className={`flex items-center gap-2 font-bold text-lg ${scenario.status === 'Pass' ? 'text-green-600' : 'text-red-600'}`}>
                                 {scenario.status === 'Pass' ? <CheckCircle className="w-6 h-6"/> : <XCircle className="w-6 h-6"/>}
                                 {scenario.status === 'Pass' ? '적정 (Pass)' : '위반 (Fail)'}
                             </div>
                             <p className="text-xs text-slate-400 mt-2">Last check: {new Date(scenario.timestamp).toLocaleDateString()}</p>
                        </div>
                    </div>

                    {/* Right: Visual Evidence */}
                    <div className="w-2/3 flex flex-col">
                        <h3 className="text-sm font-bold text-slate-500 uppercase mb-2 flex items-center gap-2">
                            <Eye className="w-4 h-4"/> 분석 증빙 자료 (Visual Evidence)
                        </h3>
                        <div className="flex-1 bg-slate-200 rounded-lg border border-slate-300 p-4 shadow-inner min-h-[400px]">
                            <GenericDocViewer scenario={scenario} />
                        </div>
                    </div>
                </div>
            </motion.div>
        </div>
    );
};

interface ScenarioManagerProps {
  scenarios: Scenario[];
  onAddScenario: (scenario: Scenario) => void;
}

const ScenarioManager: React.FC<ScenarioManagerProps> = ({ scenarios, onAddScenario }) => {
  const [filterArea, setFilterArea] = useState<AuditAreaCode | 'ALL' | 'NEW'>('ALL');
  const [searchTerm, setSearchTerm] = useState('');
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [selectedScenario, setSelectedScenario] = useState<Scenario | null>(null);

  const filteredScenarios = scenarios.filter(scenario => {
    let matchesArea = false;
    if (filterArea === 'ALL') {
        matchesArea = true;
    } else if (filterArea === 'NEW') {
        matchesArea = scenario.isNew === true;
    } else {
        matchesArea = scenario.areaCode === filterArea;
    }
    
    const matchesSearch = scenario.title.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesArea && matchesSearch;
  });

  const handleAddScenarioData = (data: { title: string, description: string, areaCode: AuditAreaCode, risk: 'High' | 'Medium' | 'Low', type: 'Structured' | 'Unstructured' }) => {
    // ... (Keep existing add logic)
    const newScenario: Scenario = {
      id: `${data.areaCode}-${Date.now()}`,
      areaCode: data.areaCode,
      title: data.title,
      description: data.type === 'Structured' 
        ? `SQL 규칙 검증: ${AUDIT_AREAS.find(a=>a.code === data.areaCode)?.name} 마스터 데이터 무결성 점검`
        : `AI 문서 분석: ${AUDIT_AREAS.find(a=>a.code === data.areaCode)?.name} 관련 증빙 문서와 시스템 데이터 대조`,
      detailedDescription: data.description,
      status: 'Pass', // New scenarios are initially compliant
      risk: data.risk,
      type: data.type,
      isNew: true, // Manual add also counts as new
      timestamp: new Date().toISOString(),
      evidenceUrl: '', 
    };
    onAddScenario(newScenario);
    setIsAddModalOpen(false);
  };

  const RiskIndicator = ({ risk }: { risk: 'High' | 'Medium' | 'Low' }) => {
    const colors = {
      High: 'bg-red-500',
      Medium: 'bg-yellow-500',
      Low: 'bg-green-500',
    };
    return (
      <div className="flex items-center gap-2">
        <div className={`w-2 h-2 rounded-full ${colors[risk]}`} />
        <span className="text-xs font-medium text-slate-500">{risk}</span>
      </div>
    );
  };
  
  return (
    <div className="p-4 sm:p-6 lg:p-8 h-full flex flex-col">
      <AnimatePresence>
        {isAddModalOpen && <AddScenarioModal onClose={() => setIsAddModalOpen(false)} onAdd={handleAddScenarioData} />}
        {selectedScenario && <ScenarioDetailModal scenario={selectedScenario} onClose={() => setSelectedScenario(null)} />}
      </AnimatePresence>

      <div className="mb-6 hidden lg:block">
        <h2 className="text-2xl font-bold text-slate-900">시나리오 관리자 (Scenario Manager)</h2>
        <p className="text-slate-500 mt-1">AI가 생성하고 관리하는 {scenarios.length}개의 자동화 감사 시나리오입니다.</p>
      </div>

      {/* Filters */}
      <div className="flex flex-col md:flex-row gap-4 mb-6">
        <div className="relative flex-1">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 w-5 h-5" />
          <input
            type="text"
            placeholder="시나리오 검색..."
            className="w-full pl-11 pr-4 py-3 rounded-lg border border-slate-200 bg-white focus:outline-none focus:ring-2 focus:ring-blue-500"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </div>
        <button 
          onClick={() => setIsAddModalOpen(true)}
          className="flex items-center justify-center gap-2 px-4 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 shadow-sm transition-colors"
        >
          <Plus className="w-5 h-5" />
          <span>새 시나리오 추가</span>
        </button>
      </div>

      {/* Area Filter Tabs */}
      <div className="mb-6 overflow-x-auto">
        <div className="flex border-b border-slate-200">
          <button onClick={() => setFilterArea('ALL')} className={`px-4 py-2 text-sm font-medium transition-colors whitespace-nowrap ${filterArea === 'ALL' ? 'border-b-2 border-blue-600 text-blue-600' : 'text-slate-500 hover:bg-slate-100'}`}>
            전체
          </button>
          <button onClick={() => setFilterArea('NEW')} className={`px-4 py-2 text-sm font-medium transition-colors whitespace-nowrap flex items-center gap-1 ${filterArea === 'NEW' ? 'border-b-2 border-blue-600 text-blue-600' : 'text-slate-500 hover:bg-slate-100'}`}>
            <Sparkles className="w-3 h-3" /> 신규 (New)
          </button>
          {AUDIT_AREAS.map(area => (
            <button key={area.code} onClick={() => setFilterArea(area.code)} className={`px-4 py-2 text-sm font-medium transition-colors whitespace-nowrap ${filterArea === area.code ? 'border-b-2 border-blue-600 text-blue-600' : 'text-slate-500 hover:bg-slate-100'}`}>
              {area.name}
            </button>
          ))}
        </div>
      </div>
      
      {/* Scenario Cards Grid */}
      <div className="flex-1 overflow-y-auto pr-2 -mr-2">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredScenarios.length > 0 ? (
            filteredScenarios.map((scenario) => (
            <div key={scenario.id} className={`bg-white border rounded-xl shadow-sm p-5 flex flex-col relative overflow-hidden hover:shadow-md transition-shadow ${scenario.isNew ? 'border-indigo-200 ring-2 ring-indigo-50' : 'border-slate-200'}`}>
               {scenario.isNew && (
                <div className="absolute top-0 right-0">
                  <div className="px-3 py-1 bg-gradient-to-r from-blue-600 to-indigo-600 text-white text-xs font-bold" style={{ clipPath: 'polygon(100% 0, 100% 100%, 0 100%, 15% 50%, 0 0)'}}>
                    <span className="flex items-center gap-1"><Sparkles className="w-3 h-3"/> AI Rec</span>
                  </div>
                </div>
              )}
              <div className="flex justify-between items-start mb-3">
                <span className="px-2 py-1 rounded bg-slate-100 text-slate-600 text-xs font-bold">{scenario.areaCode}</span>
                <RiskIndicator risk={scenario.risk} />
              </div>
              <h3 className="text-base font-bold text-slate-900 mb-2 flex-1">{scenario.title}</h3>
              <p className="text-xs text-slate-500 mb-4 line-clamp-2">{scenario.description}</p>
              <div className="flex justify-between items-center border-t border-slate-100 pt-3 mt-auto">
                <div className={`inline-flex items-center space-x-1.5 text-xs font-medium ${ scenario.status === 'Pass' ? 'text-emerald-700' : 'text-red-700' }`}>
                  {scenario.status === 'Pass' ? <CheckCircle className="w-4 h-4" /> : <XCircle className="w-4 h-4" />}
                  <span>{scenario.status === 'Pass' ? '적정' : '위반'}</span>
                </div>
                <button 
                    onClick={() => setSelectedScenario(scenario)}
                    className="flex items-center gap-1 text-slate-600 hover:text-blue-600 text-xs font-medium"
                >
                  <Paperclip className="w-3 h-3" />
                  상세 보기
                </button>
              </div>
            </div>
            ))
          ) : (
            <div className="col-span-full flex flex-col items-center justify-center p-12 text-slate-400">
                <Search className="w-12 h-12 mb-3 opacity-20" />
                <p>조건에 맞는 시나리오가 없습니다.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ScenarioManager;
